config/routes.rb
Rails.application.routes.draw do

    resources :fixes do
      resources :assignments
      resources :appointments
    end
    
    resources :customers
    resources :service_providers
    

end

app/models/fix.rb
class Fix < ActiveRecord::Base
	# enum types: {
	# 	plumbing: 1,
	# 	electrical: 2,
	# 	carpenting: 3,
	# 	painting: 4,
	# 	pest_control: 5,
	# 	appliances: 6,
	# 	other: 7 
	# }

	enum status: {
		first_sp_assigned: 1,
		alt_sp_assigned: 2,
		first_apt_fixed: 3,
		next_apt_fixed: 4,
		sp_geared_up: 5,
		sp_on_way: 6,
		sp_reached: 7,
		estimate_given: 8,
		estimate_approved: 9,
		estimate_rejected: 10,
		job_in_process: 11,
		job_finished: 12,
		money_collected: 13,
		commission_collected: 14 
	}

	enum flag_reason: {
		sp_phone_off: 1,
		sp_unavailable: 2,
		customer_phone_off: 3,
		customer_unavailable: 4,
		apt_missed: 5,
		unsatisfactory_service: 6,
		pricing_issue: 7,
		no_sp_available: 8
	}

	belongs_to :field_type
	belongs_to :customer
	has_many 	:assignments
	has_many 	:service_providers, through: :assignments
	has_many 	:appointments
	has_one		:history


	# change and handle via associations
	def current_sp
		sp_id = self.assignments.last.service_provider_id
		ServiceProvider.find(sp_id)
	end

	def get_status
		Fix.statuses[self.status]
	end

	def current_apt
		self.appointments.last
	end

	def current_assignment
		self.assignments.last
	end

	def criticality
		td = Time.now - self.current_apt.time
		if td > 10000
			0
		elsif (0 < td) && (td < 10000)
			1
		elsif td < 0
			2
		end
	end

	def criticality_class
		case self.criticality
		when 0
			"info"
		when 1
			"warning"
		when 2
			"danger"
		end
	end


	def status_obj
		{ criticality: criticality, criticality_class: criticality_class, }
	end

	def sorted_history
		nodes = []
		self.assignments.each  { |a| nodes << a }
		self.appointments.each { |a| nodes << a }
		nodes.sort {|x,y| x.created_at <=> y.created_at }
	end


	def history_str
		result = ""

		sorted_history.each do |e|
			ac  = e.created_at.to_formatted_s(:short)
			result << "<em>(" + ac + ")</em>"

			case e.class.name
			when "Assignment"
				spn = e.service_provider.name
				result << " SP => " + spn + ";"
			when "Appointment"
				at  = e.time.to_formatted_s(:long)
				result << " Apt => " + at + ";"
			else
				raise "error!"
			end

		end
		result
	end


end

app/controllers/fixes_controller.rb
class FixesController < ApplicationController
  before_action :set_fix, only: [:show, :edit, :update, :destroy]

  # GET /fixes
  # GET /fixes.json
  def index
    @fixes = Fix.all
    @assignment = Assignment.new
    @appointment = Appointment.new
  end

  # GET /fixes/1
  # GET /fixes/1.json
  def show
  end

  # GET /fixes/new
  def new
    @fix = Fix.new
  end

  # GET /fixes/1/edit
  def edit
  end

  # POST /fixes
  # POST /fixes.json
  def create
    @fix = Fix.new(fix_params)

    respond_to do |format|
      if @Fix.save
        format.html { redirect_to @fix, notice: 'fix was successfully created.' }
        format.json { render :show, status: :created, location: @fix }
      else
        format.html { render :new }
        format.json { render json: @Fix.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fixes/1
  # PATCH/PUT /fixes/1.json
  def update
    respond_to do |format|
      if @fix.update(fix_params)
        format.html { redirect_to @fix, notice: 'fix was successfully updated.' }
        format.json { render :show, status: :ok, location: @fix }
      else
        format.html { render :edit }
        format.json { render json: @Fix.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fixes/1
  # DELETE /fixes/1.json
  def destroy
    @fix.destroy
    respond_to do |format|
      format.html { redirect_to fixes_url, notice: 'fix was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fix
      @fix = Fix.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fix_params
      params.require(:fix).permit!
    end
end

app/views/fixes/_fix.html.erb
  <tr>
    <!-- <th scope="row">1</th> -->
    <td>
      <%= link_to fix.customer.name, fix.customer %> </br>
      <%= fix.customer.phone %> <br/>
      <%= fix.customer.primary_address.line1 %> <%= fix.customer.primary_address.line2 %> <br/>
      near <%= fix.customer.primary_address.line3 %> <br/>
      <%= fix.customer.primary_address.line5 %>, <%= fix.customer.primary_address.line6 %>
    </td>

    <td>
      <%= fix.field_type.name %> Job<br/>
      <div class="progress">
        <div class="progress-bar progress-bar-<%= fix.criticality_class %>" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
          3
        </div>
      </div>     
    </td>
    
    <td>
      <%= link_to fix.current_sp.name, fix.current_sp %> <br/>
      <%= fix.current_sp.phone %> <br/>
      <%= link_to "Change", new_fix_assignment_path(fix), { :remote => true, 'data-toggle' => "modal", 'data-target' => "#sp-modal" } %>
    </td>

    <td>
      <%= fix.current_apt.time.to_formatted_s(:long) %> <br/>
      <%= link_to "Change", new_fix_appointment_path(fix), { :remote => true, 'data-toggle' => "modal", 'data-target' => "#apt-modal" } %>
    </td>

    <td>
      <%= fix.history_str.gsub(/;/, '<br>').html_safe %>
    </td>


    <td><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></td>
  </tr>



<!-- Modal -->
<div class="modal fade" id="sp-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">


<div class="dropdown">
    <%= simple_form_for [fix, @assignment] do |f| %>
      <%= f.collection_select(:service_provider_id, ServiceProvider.all, :id, :name) %>
      <%= f.submit %>
    <% end %>
</div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>



<!-- Modal -->
<div class="modal fade" id="apt-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">


<div class="dropdown">
    <%= simple_form_for [fix, @appointment] do |f| %>
      <%= f.input :time, as: :datetime, class: 'hidden' %>
      <%= f.submit %>
    <% end %>
</div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>



<script type="text/javascript">
$(document).on('ready', function() {
  // $('#mymodal').modal();
});
</script>

app/views/fixes/_fix_status.html.erb
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
    <span class="sr-only">60% Complete</span>
  </div>
</div>

app/views/fixes/index.html.erb
<% provide(:title, "All Fixes") %>
<h1>All fixes</h1>

<table class="table .table-striped">
  <thead>
  	<tr>
    	<th>Customer Details</th>
    	<th>Status</th> 
    	<th>Service Provider</th>
      <th>Next Apt</th>
      <th>History</th>
    	<th>Actions</th>
  	</tr>
  </thead>

	<tbody>
		<%= render @fixes %>
	</tbody>

</table>

app/views/fixes/show.html.erb
<table style="width:100%">

  <%= render @fix %>

<table style="width:100%">